server:
  port: 7777
  servlet:
    context-path: /uaa

spring:
  application:
    name: authority-auth-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: DEBUG
