server:
  port: 5555

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
#    health:
#      show-details: always
#  security:
#    enabled: false

zuul:
  routes:
    client-a:
      path: /client/**
      serviceId: eureka-client
