server:
  port: 8081

spring:
  application:
    name: demo-client

eureka:
  client:
    security:
      basic:
        user: admin
        password: hexiaogou
    service-url:
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:8761/eureka/