server:
  port: 8081

spring:
  application:
    name: demo-client

eureka:
  client:
    securePortEnabled: true
    ssl:
      key-store: client.p12
      key-store-password: Client
    service-url:
      defaultZone: https://localhost:8761/eureka/