server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:server.p12
    key-store-password: Spring Cloud
    key-store-type: PKCS12
    key-alias: server

spring:
  application:
    name: eureka-server



eureka:
  instance:
    hostname: localhost
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
    home-page-url: https://${eureka.instance.hostname}:${server.port}/
    status-page-url: https://${eureka.instance.hostname}:${server.port}/
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false