server:
  port: 8010

spring:
  application:
    name: feign-gzip

feign:
  compression:
    request:
      enabled: true
      mime-types:
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048
    response:
      enabled: true
logging:
  level:
    com.jie.service.FeignGzipApplication: debug


