server:
  port: 5555

spring:
  application:
    name: gray-zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
  instance:
    prefer-ip-address: true

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: /*
  endpoint:
    health:
      show-details: always

zuul:
  routes:
    gray-zuul-client:
      path: "/client/**"
      serviceId: gray-zuul-client
