server:
  port: 8011
spring:
  application:
    name: venus-feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: false      