server:
  port: 5555

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    eureka-a:
      path: /client/**
      serviceId: eureka-client

